openapi: 3.0.0
info:
  title: Tapiro API
  description: API for AI-Driven Personalized Advertising System
  version: 1.0.0
  contact: { name: Tapiro Support, email: tapirosupport@gmail.com }
tags:
  - name: Authentication
    description: Endpoints related to OAuth2 authentication and authorization
  - name: User Management
    description: Operations for user registration, profile management, and deletion
servers:
  - url: https://virtserver.swaggerhub.com/CHAMATHDEWMINA25/TAPIRO/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: https://api.tapiro.com/v1
    description: Production API
  - url: http://localhost:${PORT}
    description: Development API
security:
  - oauth2:
      - user:read
      - user:write
      - store:read
      - store:write
paths:
  /auth/token:
    post:
      tags:
        - Authentication
      summary: Get OAuth2 Token
      description: Exchange authorization code for access token.
      operationId: authTokenPOST
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/auth_token_body"
        required: true
      responses:
        "200":
          description: Token response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "401":
          description: Unauthorized
      x-swagger-router-controller: Authentication

  /auth/authorize:
    get:
      tags:
        - Authentication
      summary: Authorize User
      description: Redirect to OAuth2 authorization page.
      operationId: authAuthorizeGET
      parameters:
        - name: response_type
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - code
        - name: client_id
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: redirect_uri
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        "302":
          description: Redirect to login/consent page
      x-swagger-router-controller: Authentication

  /users:
    post:
      tags:
        - User Management
      summary: Register User
      description: Create a new user (customer or store).
      operationId: usersPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
        required: true
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid input
      x-swagger-router-controller: Authentication

  /users/{userId}:
    get:
      tags:
        - User Management
      summary: Get User Profile
      description: Get User Profile by ID.
      operationId: usersUserIdGET
      parameters:
        - name: userId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: User data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "403":
          description: Forbidden
      security:
        - oauth2:
            - user:read
      x-swagger-router-controller: Authentication

    put:
      tags:
        - User Management
      summary: Update User Profile
      description: Update User Profile by ID.
      operationId: usersUserIdPUT
      parameters:
        - name: userId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
        required: true
      responses:
        "200":
          description: Updated user data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "403":
          description: Forbidden
      security:
        - oauth2:
            - user:write
      x-swagger-router-controller: Authentication

    delete:
      tags:
        - User Management
      summary: Delete User
      description: Delete User Profile by ID.
      operationId: usersUserIdDELETE
      parameters:
        - name: userId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "204":
          description: User deleted
        "403":
          description: Forbidden
      security:
        - oauth2:
            - user:write
      x-swagger-router-controller: Authentication

  /stores/{storeId}/ads:
    post:
      tags: [Ad Management]
      summary: Create new advertisement
      operationId: createAd
      parameters:
        - name: storeId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ad"
        required: true
      responses:
        "201":
          description: Ad created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ad"
      security:
        - oauth2: [store:write]
      x-swagger-router-controller: Advertisements

    get:
      tags: [Ad Management]
      summary: List store ads
      operationId: listAds
      parameters:
        - name: storeId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: List of ads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ad"
      security:
        - oauth2: [store:read]
      x-swagger-router-controller: Advertisements

  /stores/{storeId}/ads/{adId}:
    put:
      tags: [Ad Management]
      summary: Update specific ad
      operationId: updateAd
      parameters:
        - name: storeId
          in: path
          required: true
          schema: { type: string }
        - name: adId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ad"
        required: true
      responses:
        "200":
          description: Updated ad
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ad"
      security:
        - oauth2: [store:write]
      x-swagger-router-controller: Advertisements

    delete:
      tags: [Ad Management]
      summary: Delete specific ad
      operationId: deleteAd
      parameters:
        - name: storeId
          in: path
          required: true
          schema: { type: string }
        - name: adId
          in: path
          required: true
          schema: { type: string }
      responses:
        "204":
          description: Ad deleted
      security:
        - oauth2: [store:write]
      x-swagger-router-controller: Advertisements

  /stores/{storeId}/qr:
    get:
      tags: [QR Code]
      summary: Generate QR code
      operationId: generateQR
      parameters:
        - name: storeId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: QR code image
          content:
            image/png:
              schema: { type: string, format: binary }
      security:
        - oauth2: [store:write]
      x-swagger-router-controller: QRcodes

  /scan:
    post:
      tags: [QR Code]
      summary: Process QR scan
      operationId: processScan
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/qr_data"
        required: true
      responses:
        "200":
          description: Ads for scanned store
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdResponse"
      security: []
      x-swagger-router-controller: QRcodes

  /users/{userId}/ads:
    get:
      tags: [Recommendations]
      summary: Get personalized ads
      operationId: getPersonalizedAds
      parameters:
        - name: userId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Personalized ads
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdResponse"
      security:
        - oauth2: [user:read]
      x-swagger-router-controller: Recommendations

  /recommendations:
    post:
      tags: [Recommendations]
      summary: Trigger personalization
      operationId: triggerRecommendations
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id: { type: string }
                store_id: { type: string }
        required: true
      responses:
        "202":
          description: Recommendation job started
      security:
        - oauth2: [store:write, user:read]
      x-swagger-router-controller: Recommendations

  /users/{userId}/preferences:
    put:
      tags: [User Management]
      summary: Update preferences
      operationId: updatePreferences
      parameters:
        - name: userId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User_preferences"
        required: true
      responses:
        "200":
          description: Updated preferences
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User_preferences"
      security:
        - oauth2: [user:write]
      x-swagger-router-controller: UserController

  /users/{userId}/purchases:
    post:
      tags: [User Management]
      summary: Log purchase
      operationId: logPurchase
      parameters:
        - name: userId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Purchase"
        required: true
      responses:
        "201":
          description: Purchase logged
      x-swagger-router-controller: UserController

  /stores/{storeId}/analytics/engagement:
    get:
      tags: [Analytics]
      summary: Get engagement analytics
      operationId: getEngagement
      parameters:
        - name: storeId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Engagement metrics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Analytics"
      security:
        - oauth2: [store:read]
      x-swagger-router-controller: AnalyticsController

  /stores/{storeId}/analytics/demographics:
    get:
      tags: [Analytics]
      summary: Get demographic analytics
      operationId: getDemographics
      parameters:
        - name: storeId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Demographic data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Analytics"
      security:
        - oauth2: [store:read]
      x-swagger-router-controller: AnalyticsController

components:
  schemas:
    User:
      required:
        - email
        - role
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
        role:
          type: string
          enum:
            - customer
            - store
        preferences:
          $ref: "#/components/schemas/User_preferences"
        privacy_settings:
          $ref: "#/components/schemas/User_privacy_settings"
      example:
        preferences:
          purchase_history:
            - purchase_history
            - purchase_history
          categories:
            - categories
            - categories
        role: customer
        privacy_settings:
          data_sharing: true
          anonymized_id: anonymized_id
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        email: "johndoe@gmail.com"
    UserCreate:
      required:
        - email
        - password
        - role
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          writeOnly: true
        role:
          type: string
          enum:
            - customer
            - store
    UserUpdate:
      type: object
      properties:
        email:
          type: string
          format: email
        preferences:
          type: object
        privacy_settings:
          type: object
    Token:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
        refresh_token:
          type: string
      example:
        access_token: access_token
        refresh_token: refresh_token
        token_type: token_type
        expires_in: 0
    auth_token_body:
      required:
        - grant_type
        - client_id
        - client_secret
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - authorization_code
            - refresh_token
        code:
          type: string
        redirect_uri:
          type: string
        client_id:
          type: string
        client_secret:
          type: string
        refresh_token:
          type: string
    User_preferences:
      type: object
      properties:
        categories:
          type: array
          items:
            type: string
        purchase_history:
          type: array
          items:
            type: string
      example:
        purchase_history:
          - purchase_history
          - purchase_history
        categories:
          - categories
          - categories
    User_privacy_settings:
      type: object
      properties:
        data_sharing:
          type: boolean
        anonymized_id:
          type: string
          readOnly: true
      example:
        data_sharing: true
        anonymized_id: anonymized_id
    Ad:
      type: object
      required: [title, target_categories]
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title: { type: string }
        description: { type: string }
        target_categories:
          type: array
          items: { type: string }
        media_url: { type: string }
        validity_period:
          type: object
          properties:
            start: { type: string, format: date-time }
            end: { type: string, format: date-time }
    AdResponse:
      type: object
      properties:
        store_id: { type: string }
        ads:
          type: array
          items:
            $ref: "#/components/schemas/Ad"
    qr_data:
      type: object
      properties:
        store_id: { type: string }
        user_id: { type: string }
    Purchase:
      type: object
      required: [store_id, items]
      properties:
        store_id: { type: string }
        items:
          type: array
          items:
            type: object
            properties:
              product_id: { type: string }
              category: { type: string }
    Analytics:
      type: object
      properties:
        top_categories:
          type: array
          items: { type: string }
        avg_engagement_time: { type: number }

  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-zuxebycdcmuazvo8.us.auth0.com/authorize
          tokenUrl: https://dev-zuxebycdcmuazvo8.us.auth0.com/oauth/token
          scopes:
            user:read: Read user data
            user:write: Modify user data
            store:read: Read store data
            store:write: Modify store data
