services:
  backend:
    build:
      context: ./backend
      target: development
    container_name: tapiro-API
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:3000
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - issuerBaseURL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - tapiro-net

  web:
    build:
      context: ./web
      target: development
    container_name: tapiro-web
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3000
    ports:
      - "3001:5173"
    networks:
      - tapiro-net
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: tapiro-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - tapiro-net

networks:
  tapiro-net:

volumes:
  redis-data:
