services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:3000
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - issuerBaseURL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: tapiro-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
