/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Create a new regular user account
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Store
         * @description Create a new store account
         */
        post: operations["registerStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile
         * @description Get authenticated user's profile
         */
        get: operations["getUserProfile"];
        /**
         * Update User Profile
         * @description Update authenticated user's profile
         */
        put: operations["updateUserProfile"];
        post?: never;
        /**
         * Delete User Profile
         * @description Delete authenticated user's profile
         */
        delete: operations["deleteUserProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Store Profile
         * @description Get authenticated store's profile
         */
        get: operations["getStoreProfile"];
        /**
         * Update Store Profile
         * @description Update authenticated store's profile
         */
        put: operations["updateStoreProfile"];
        post?: never;
        /**
         * Delete Store Profile
         * @description Delete authenticated store's profile
         */
        delete: operations["deleteStoreProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit user data
         * @description Submit purchase/search history for a user (authenticated via API key)
         */
        post: operations["submitUserData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user preferences
         * @description Retrieve preferences for targeted advertising
         */
        get: operations["getUserPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user preferences
         * @description Get the authenticated user's preferences
         */
        get: operations["getUserOwnPreferences"];
        /**
         * Update user preferences
         * @description Update the user's interest preferences and related settings
         */
        put: operations["updateUserPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/preferences/opt-in/{storeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Opt in to store data collection
         * @description Removes a store from the user's opt-out list to allow data collection
         */
        post: operations["optInToStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/preferences/opt-out/{storeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Opt out from store data collection
         * @description Adds a store to the user's opt-out list to prevent data collection
         */
        post: operations["optOutFromStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description Returns all active API keys for the store
         */
        get: operations["getApiKeys"];
        put?: never;
        /**
         * Generate new API key
         * @description Generates a new API key for the authenticated store
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/api-keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke API key
         * @description Revokes a specific API key
         */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/api-keys/{keyId}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get API key usage statistics
         * @description Returns usage data for a specific API key
         */
        post: operations["getApiKeyUsage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Comprehensive health check that verifies API and dependencies
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simple Uptime Check
         * @description Simple ping endpoint for uptime monitoring
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update User Metadata
         * @description Update Auth0 metadata for the authenticated user
         */
        put: operations["updateUserMetadata"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/metadata/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get User Metadata
         * @description Retrieve Auth0 metadata for the authenticated user
         */
        post: operations["getUserMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Distribution of attribute values (0.0-1.0) */
        AttributeDistribution: {
            [key: string]: number;
        };
        User: {
            readonly userId?: string;
            /** @description Auth0 user ID */
            auth0Id: string;
            /** Format: email */
            email: string;
            username?: string;
            phone?: string;
            /** @description User interest preferences with taxonomy categorization */
            preferences?: components["schemas"]["PreferenceItem"][];
            privacySettings?: {
                /** @default false */
                dataSharingConsent: boolean;
                /** @default false */
                anonymizeData: boolean;
                /** @description List of store IDs user has opted into */
                optInStores?: string[];
                /** @description List of store IDs user has opted out from */
                optOutStores?: string[];
            };
            dataAccess?: {
                /** @description List of allowed domains for data access */
                allowedDomains?: string[];
            };
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        Store: {
            readonly storeId?: string;
            /** @description Auth0 organization ID */
            auth0Id: string;
            name: string;
            address: string;
            /** @description Hashed API keys */
            readonly apiKeys?: string[];
            webhooks?: {
                /** Format: uri */
                url: string;
                events: ("purchase" | "opt-out")[];
            }[];
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        UserCreate: {
            preferences?: components["schemas"]["PreferenceItem"][];
            /** @description User's consent for data sharing */
            dataSharingConsent: boolean;
        };
        StoreCreate: {
            name: string;
            address: string;
            webhooks?: {
                /** Format: uri */
                url?: string;
                events?: ("purchase" | "opt-out")[];
            }[];
        };
        UserUpdate: {
            /** @description User interest preferences with taxonomy categorization */
            preferences?: components["schemas"]["PreferenceItem"][];
            privacySettings?: {
                dataSharingConsent?: boolean;
                anonymizeData?: boolean;
                optInStores?: string[];
                optOutStores?: string[];
            };
            dataAccess?: {
                allowedDomains?: string[];
            };
        };
        ApiKey: {
            /** Format: uuid */
            readonly keyId?: string;
            readonly prefix?: string;
            /** @description Name for the API key */
            name?: string;
            /** Format: date-time */
            readonly createdAt?: string;
            /** @enum {string} */
            status?: "active" | "revoked";
        };
        UserData: {
            /** @description User's email address */
            email: string;
            /**
             * @description Type of data being submitted
             * @enum {string}
             */
            dataType: "purchase" | "search";
            /** @description Array of data entries */
            entries: (components["schemas"]["PurchaseEntry"] | components["schemas"]["SearchEntry"])[];
            /** @description Additional information about the collection event */
            metadata?: {
                /** @description Optional user ID if known */
                userId?: string;
                /** @description Source of the data (web, mobile, pos, etc) */
                source?: string;
                /** @description Type of device used */
                deviceType?: string;
                /** @description Unique identifier for the user session */
                sessionId?: string;
            };
        };
        PurchaseEntry: {
            /** Format: date-time */
            timestamp: string;
            items: components["schemas"]["PurchaseItem"][];
            /** Format: float */
            totalAmount?: number;
        };
        PurchaseItem: {
            sku?: string;
            name: string;
            /** @description Category ID (e.g., "101") or name (e.g., "smartphones") */
            category: string;
            /** @default 1 */
            quantity: number;
            /** Format: float */
            price?: number;
            attributes?: components["schemas"]["ItemAttributes"];
        };
        /** @description Category-specific attributes */
        ItemAttributes: {
            /** @enum {string} */
            price_range?: "budget" | "mid_range" | "premium" | "luxury";
            brand?: string;
            color?: string;
            material?: string;
            style?: string;
            room?: string;
            size?: string;
            feature?: string;
            season?: string;
            gender?: string;
        };
        SearchEntry: {
            /** Format: date-time */
            timestamp: string;
            query: string;
            category?: string;
            results?: number;
            clicked?: string[];
        };
        UserPreferences: {
            userId?: string;
            preferences?: components["schemas"]["PreferenceItem"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        UserPreferencesUpdate: {
            /** @description User interest preferences with taxonomy categorization */
            preferences?: components["schemas"]["PreferenceItem"][];
        };
        PreferenceItem: {
            /** @description Category ID or name (e.g., "101" or "smartphones") */
            category: string;
            /**
             * Format: float
             * @description Preference score (0.0-1.0)
             */
            score: number;
            /** @description Category-specific attribute preferences */
            attributes?: {
                price_range?: {
                    /** Format: float */
                    budget?: number;
                    /** Format: float */
                    mid_range?: number;
                    /** Format: float */
                    premium?: number;
                    /** Format: float */
                    luxury?: number;
                };
                color?: components["schemas"]["AttributeDistribution"];
                brand?: components["schemas"]["AttributeDistribution"];
                material?: components["schemas"]["AttributeDistribution"];
                style?: components["schemas"]["AttributeDistribution"];
                room?: components["schemas"]["AttributeDistribution"];
                size?: components["schemas"]["AttributeDistribution"];
                feature?: components["schemas"]["AttributeDistribution"];
                season?: components["schemas"]["AttributeDistribution"];
                gender?: components["schemas"]["AttributeDistribution"];
            };
        };
        StoreUpdate: {
            name?: string;
            address?: string;
            webhooks?: {
                /** Format: uri */
                url?: string;
                events?: ("purchase" | "opt-out")[];
            }[];
        };
        ApiKeyCreate: {
            /** @description Name for the API key */
            name?: string;
        };
        ApiKeyList: components["schemas"]["ApiKey"][];
        ApiKeyUsage: {
            keyId?: string;
            prefix?: string;
            name?: string;
            totalRequests?: number;
            methodBreakdown?: {
                [key: string]: number;
            };
            endpointBreakdown?: {
                [key: string]: number;
            };
            dailyUsage?: {
                /** Format: date */
                date?: string;
                count?: number;
            }[];
        };
        HealthStatus: {
            /**
             * @description Overall health status of the Health
             * @enum {string}
             */
            status?: "healthy" | "degraded" | "unhealthy";
            /**
             * Format: date-time
             * @description Time of health check
             */
            timestamp?: string;
            /** @description Service name */
            service?: string;
            dependencies?: {
                /** @enum {string} */
                database?: "connected" | "disconnected" | "degraded";
                /** @enum {string} */
                cache?: "connected" | "disconnected" | "degraded";
                /** @enum {string} */
                auth?: "connected" | "disconnected" | "degraded" | "unknown";
            };
        };
        Error: {
            /**
             * Format: int32
             * @description HTTP status code
             */
            code: number;
            /** @description Error message */
            message: string;
            /** @description Additional error details if available */
            details?: string;
        };
        PingStatus: {
            /** @enum {string} */
            status?: "ok";
            /** Format: date-time */
            timestamp?: string;
        };
        UserMetadataUpdate: {
            /**
             * @description The type of registration (user or store)
             * @enum {string}
             */
            registrationType?: "user" | "store";
            /** @description Whether registration process is complete */
            registrationComplete?: boolean;
        };
        UserMetadataResponse: {
            /** @description Whether metadata was updated successfully */
            updated?: boolean;
            /** @description User metadata from Auth0 */
            metadata?: {
                /**
                 * @description The type of registration
                 * @enum {string}
                 */
                registrationType?: "user" | "store";
                /** @description Whether registration process is complete */
                registrationComplete?: boolean;
            };
        };
    };
    responses: {
        /** @description Bad request - invalid input */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized - authentication required */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden - insufficient permissions */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found - resource doesn't exist */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict - resource already exists */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    registerStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreate"];
            };
        };
        responses: {
            /** @description Store created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description User profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getStoreProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateStoreProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUpdate"];
            };
        };
        responses: {
            /** @description Store profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteStoreProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store profile deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    submitUserData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserData"];
            };
        };
        responses: {
            /** @description Data accepted for processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UserPreferences retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserOwnPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User preferences retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateUserPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferencesUpdate"];
            };
        };
        responses: {
            /** @description Preferences updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    optInToStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the store to opt in to */
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully opted in to store */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    optOutFromStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the store to opt out from */
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully opted out from store */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of API keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description API key created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getApiKeyUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: date
                     * @description Optional start date for filtering usage data
                     */
                    startDate?: string;
                    /**
                     * Format: date
                     * @description Optional end date for filtering usage data
                     */
                    endDate?: string;
                };
            };
        };
        responses: {
            /** @description API key usage statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyUsage"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Simple response indicating the API is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingStatus"];
                };
            };
        };
    };
    updateUserMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserMetadataUpdate"];
            };
        };
        responses: {
            /** @description Metadata updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMetadataResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMetadataResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
