name: Development Docker CI

on:
  push:
    branches: ["Development"]
  pull_request:
    branches: ["Development"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image (Development)
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/dockerfile
          tags: backend-dev
          cache-from: type=local,dest=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build web image (Development)
        uses: docker/build-push-action@v2
        with:
          context: ./web
          file: ./web/dockerfile.dev
          tags: web-dev
          cache-from: type=local,dest=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Start containers (Development)
        run: docker-compose -f compose.yml up -d --build

      - name: Integration tests
        run: |
          sleep 10 # give containers time to start
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3000/auth/healthcheck
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3001

      - name: Stop containers (Development)
        run: docker-compose -f compose.yml down

      - name: Run backend tests
        run: |
          docker exec tapiro-API npm test

      - name: Run web tests
        run: |
          docker exec tapiro-web npm test
