name: CI-Prod

on:
  push:
    branches: ["Production"]
    paths:
      - "backend/**"
      - "web/**"
      - ".github/workflows/ci-prod.yml"
  pull_request:
    branches: ["Production"]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run all tests
        working-directory: backend
        run: |
          npm run test:unit
          npm run test:integration
          npm run test:api
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          directory: backend/coverage
          flags: backend

  web-tests:
    name: Web Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Add timeout
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Add retry logic for node setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
        continue-on-error: true
        id: setup-node

      # Fallback node setup if primary fails
      - name: Setup Node.js (Fallback)
        if: steps.setup-node.outcome == 'failure'
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g npm@latest

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Run all tests
        working-directory: web
        run: |
          npm run test

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          start: npm run dev
          wait-on: "http://localhost:5173"

      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          directory: web/coverage
          flags: web

  docker-tests:
    name: Docker Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Add Docker Compose setup
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # Use Docker Compose V2 syntax
      - name: Build containers
        run: docker compose -f compose.yml build

      - name: Start containers
        run: |
          docker compose -f compose.yml up -d
          sleep 30

      - name: Test container health
        run: |
          docker ps
          curl -f http://localhost:3000/health || exit 1
          curl -f http://localhost:3001/health || exit 1

      - name: Check logs for errors
        run: |
          docker compose logs backend
          docker compose logs web

      - name: Cleanup
        run: docker compose down

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [web, backend]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm ci

      - name: Run linting
        working-directory: ${{ matrix.service }}
        run: npm run lint

      - name: Run tests with coverage
        working-directory: ${{ matrix.service }}
        run: npm test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.service }}/coverage
          flags: ${{ matrix.service }}

  build:
    needs: [security, validate]
    name: Build & Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [web, backend]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/dockerfile.prod
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Production'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
