# Development stage
FROM node:18-alpine AS development
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --include=dev
COPY . .
CMD ["npm", "run", "dev", "--", "--host", "0.0.0

# Production stage (optional)
FROM nginx:alpine AS production
COPY --from=development /app/dist /usr/share/nginx/html
EXPOSE 80